/**
 * 
 */
function cslLoad (csl) {
	$.each(csl, function(index, item){
		$("#start").append('<div id="camp" class="theme-search-results-item _mb-10 theme-search-results-item-full">'
				+'<div class="theme-search-results-item-preview">'
				+'<a class="theme-search-results-item-mask-link" href="#searchResultsItem-" role="button"	data-toggle="collapse" aria-expanded="false" aria-controls="searchResultsItem-"></a>'
				+'<div class="row row-no-gutter row-eq-height">'
					+'<div class="col-md-4 ">'
						+'<div class="banner theme-search-results-item-img-full banner-">'
							+'<div class="banner-bg" style="background-image: url(./img/315x225.png);"><img style="width: 315px; height: 225px;" src="img/' + item.file + '"></div>'
							+'<a class="banner-link" href="#"></a>'
						+'</div>'
					+'</div>'
					+'<div class="col-md-8 ">'
						+'<div class="theme-search-results-item-body">'
							+'<div class="row row-eq-height" data-gutter="20">'
								+'<div class="col-md-9 ">'
									+'<h5	class="theme-search-results-item-title theme-search-results-item-title-lg">' + item.campName+ ' / ' + item.campSiteName + '</h5>'
									+'<div class="theme-search-results-item-hotel-rating">'
										+'<p class="theme-search-results-item-hotel-rating-title">'
											+'<b>' + item.rate + '</b>'
										+'</p>'
									+'</div>'
									+'<p class="theme-search-results-item-location">'
										+'<i class="fa fa-map-marker"></i>' + item.campAddr	+ '</p></div>'
								+'<div class="col-md-3 ">'
									+'<div class="theme-search-results-item-book">'
										+'<div class="theme-search-results-item-price">'
											+'<p class="theme-search-results-item-price-tag">' + item.price + '</p>'
											+'<p class="theme-search-results-item-price-sign">1박</p>'
										+'</div>'
										+'<a class="btn btn-primary-inverse btn-block theme-search-results-item-price-btn" id="' + item.campId + '">상세보기</a>'
										+'<div class="campBookmark">'
										+'<a id="myCamp' + item.siteId + '" class="theme-search-results-item-bookmark theme-search-results-item-bookmark-bottom">' 
											+'<i class="fa fa-bookmark"></i> <span>찜하기</span>'
										+'</a>'
										+'</div>'
									+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
					+'</div>'
				+'</div>'
			+'</div>'
		+'</div>');
});
}